// This is the master file of all product data. Products are stored as objects.
// Data from here served to API http://localhost:4000/api/products
// Products are currently being served from this file but will shift to a database later. 

export default {
    products: [{
            _id: "1",
            name: "TIE BELT DRESS",
            category: "Dress",
            image: "/imgs/1.jpeg",
            price: 19.99,
            brand: "M&H",
            rating: 4.2,
            numReviews: 10,
            countInStock: 10,
        },{
            _id: "2",
            name: "LEATHER BIKER JACKET",
            category: "Jacket",
            image: "/imgs/2.jpeg",
            price: 69.99,
            brand: "M&H",
            rating: 4.2,
            numReviews: 218,
            countInStock: 0,
        },{
            _id: "3",
            name: "SLEEVELESS BLACK JUMPSUIT",
            category: "Jumpsuit",
            image: "/imgs/3.jpeg",
            price: 59.99,
            brand: "M&H",
            rating: 4.8,
            numReviews: 320,
            countInStock: 10,
        },{
            _id: "4",
            name: "BUTTON FRONT PLAYSUIT",
            category: "Jumpsuit",
            image: "/imgs/4.jpeg",
            price: 23.99,
            brand: "M&H",
            rating: 4.7,
            numReviews: 291,
            countInStock: 10,
        },{
            _id: "5",
            name: "TRACK JACKET",
            category: "Jacket",
            image: "/imgs/5.jpeg",
            price: 69.99,
            brand: "M&H",
            rating: 3.9,
            numReviews: 159,
            countInStock: 10,
        },{
            _id: "6",
            name: "FLOUNCE TRIMMED ROMPER",
            category: "Jumpsuit",
            image: "/imgs/6.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 4.4,
            numReviews: 237,
            countInStock: 10,
        },{
            _id: "7",
            name: "LIGHT BLUE ROMPER",
            category: "Jumpsuit",
            image: "/imgs/7.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 4.8,
            numReviews: 338,
            countInStock: 10,
        },{
            _id: "8",
            name: "SMOCKED FLORAL PLAYSUIT",
            category: "Jumpsuit",
            image: "/imgs/8.jpeg",
            price: 19.99,
            brand: "M&H",
            rating: 4.6,
            numReviews: 402,
            countInStock: 10,
        },{
            _id: "9",
            name: "CHILL TSHIRT DRESS",
            category: "Tshirt",
            image: "/imgs/9.jpeg",
            price: 12.99,
            brand: "M&H",
            rating: 4.2,
            numReviews: 115,
            countInStock: 10,
        },{
            _id: "10",
            name: "CASUAL BODYCON DRESS",
            category: "Dress",
            image: "/imgs/10.jpeg",
            price: 59.99,
            brand: "M&H",
            rating: 4.1,
            numReviews: 96,
            countInStock: 10,
        },{
            _id: "11",
            name: "PUFF SLEEVES DRESS",
            category: "Dress",
            image: "/imgs/11.jpeg",
            price: 29.99,
            brand: "M&H",
            rating: 4.1,
            numReviews: 143,
            countInStock: 10,
        },{
            _id: "12",
            name: "COLD SHOULDER FLORAL DRESS",
            category: "Dress",
            image: "/imgs/12.jpeg",
            price: 29.99,
            brand: "M&H",
            rating: 4.2,
            numReviews: 275,
            countInStock: 10,
        },{
            _id: "13",
            name: "FLORAL PLAYSUIT DRESS",
            category: "Dress",
            image: "/imgs/13.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 3.9,
            numReviews: 81,
            countInStock: 10,
        },{
            _id: "14",
            name: "COTTON PINK TSHIRT",
            category: "Tshirt",
            image: "/imgs/14.jpeg",
            price: 9.99,
            brand: "M&H",
            rating: 4.0,
            numReviews: 183,
            countInStock: 10,
        },{
            _id: "15",
            name: "WHITE SLIM BODYSUIT",
            category: "Jumpsuit",
            image: "/imgs/15.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 4.4,
            numReviews: 237,
            countInStock: 10,
        },{
            _id: "16",
            name: "PUFF SLEEVED BLACK DRESS",
            category: "Dress",
            image: "/imgs/16.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 3.8,
            numReviews: 70,
            countInStock: 10,
        },{
            _id: "17",
            name: "WHITE SHORT DRESS",
            category: "Dress",
            image: "/imgs/17.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 4.1,
            numReviews: 63,
            countInStock: 10,
        },{
            _id: "18",
            name: "CORAL SLIM BODYSUIT",
            category: "Jumpsuit",
            image: "/imgs/18.jpeg",
            price: 39.99,
            brand: "M&H",
            rating: 4.7,
            numReviews: 249,
            countInStock: 10,
        },
    ]
}